use etlhive;
select * from healthcare;
-- Retrieve the names of all patients in the database
select name from healthcare;

--  List the unique medical conditions present in the dataset.
select distinct medical_condition  from healthcare;

-- Find the total number of doctors in the healthcare system. 
select count(*) doctor from healthcare;

-- . Retrieve the details of all female patients.  
select * from healthcare where gender='Female';

-- what is the average age of patients in the database.
select avg(age) from healthcare;

-- . Identify the patients who have more than one medical condition
select name  from healthcare group by name having count(medical_condition)>1;

--  List the names of all doctors. 
select doctor from healthcare;

-- .Identify the most common medical condition among patients
select medical_condition from healthcare group by medical_condition having count(medical_condition)>1 limit 1;

-- Find the patients who are older than 60 years and have diabetes
select * from healthcare where age> 60 and medical_condition='diabetes';

-- Calculate the total revenue generated by the healthcare system
select sum(billing_amount) from healthcare ;

-- .Find the doctor with the oldest patient.
select doctor,age from healthcare order by age desc limit 1;
select * from healthcare;

-- .Calculate the average duration of medical visits
select avg(duration) from healthcare;

-- .Give the names of patients whose name starts with A
select * from healthcare where name like 'a%';

-- .How many male and female patients are there in dataset
select gender, count(*) gender from healthcare group by gender;

-- how many patients are normal.  
select test_results,count(*) test_results from healthcare where test_results='normal';

-- .how many patients are abnormal or Inconclusive..
select test_results,count(*) from healthcare where test_results='abnormal' or test_results='inconclusive'
group by test_results;

-- .how many patients of blood group AB+ are there of age above 52. 
select blood_type,count(*) from healthcare where age > 52 and blood_type='AB+' group by blood_type;

-- how many patients have paid the bill above 24890.
select billing_amount,count(*) from healthcare where billing_amount >24890
group by billing_amount;

-- . what are the names of patients having Asthma.  
select name,medical_Condition from healthcare where medical_condition ='asthma';

--  how many patients have cancer.  
select medical_condition,count(*) from healthcare where medical_condition='cancer' 
group by medical_condition;

-- what are the names and blood groups of patients admitted to room no. 292.  
select name,blood_type,room_number from healthcare where room_number=292;

-- . how many males have Arthritis.
select medical_condition, gender, count(*) from healthcare
 where gender='male'and medical_Condition='arthritis'
group by gender;

-- How many patients were admitted to Harris and Sons hospital.
select hospital,count(*) from healthcare 
where hospital='harris and sons' 
group by hospital; 

-- 4. what are the names of patients whose Insurance Provider are Cigna.  
select name,Insurance_Provider from healthcare 
where Insurance_Provider='cigna';

-- Name the Medical Condition having patients whose ages is greater than average age
select medical_condition from healthcare 
where age > (select avg(age) from healthcare)
group by  medical_condition;

select * from healthcare  where name='michael White';